### ISSUE TITLE
prep_data = torch.load('./preprocessed_128.pt')

### ISSUE THREAD

**Issue by caixiaodou1115** [calculs-ca/Semantic-Segmentation#1]
Holle,May I ask where this 'preprocessed_128.pt' file is？When I run this  'main.py' program, this 'FileNotFoundError: [Errno 2] No such file or directory: './preprocessed_128.pt'' is displayed.I look forward to hearing from you

**Comment by lemairecarl** [comment]
Hi! Sorry, we did not expect someone to use this repo! :O

You can produce this file by using `prepare_data(preprocess=True)`  here:

https://github.com/calculs-ca/Semantic-Segmentation/blob/db8061629338ed0a7cb432dba2c4305fca197635/main.py#L175

By the way, you should also change
`preprocess_images(os.environ['PATH'])` to  `preprocess_images(os.environ['SUIM_PATH'])`

at https://github.com/calculs-ca/Semantic-Segmentation/blob/db8061629338ed0a7cb432dba2c4305fca197635/main.py#L120

Then, set your SUIM_PATH environment variable to where you have downloaded the SUIM dataset.

**Comment by caixiaodou1115** [comment]
> I am a beginner and thank you very much for your answer

**Comment by lemairecarl** [comment]
@caixiaodou1115 the code has been fixed, and there is now a new README.
